resolver: nightly-2018-04-12

ghc-options:
  vulkan-api:    -O2
  GLFW-b:        -O2
  bindings-GLFW: -O2

flags:
  vulkan-api:
    useNativeFFI-1-0: true
    useNativeFFI-1-1: false

extra-deps:
  - bindings-GLFW-3.2.1.0

packages:
  - .
  - location: ../vulkan-api
    extra-dep: true
  - location:
      git: https://github.com/bsl/GLFW-b
      commit: 311a3a3b1ba0e4525ad1e1292ef1b363645cbafe
    extra-dep: true
