resolver: nightly-2018-04-09
ghc-options:
  vulkan-api:    -O2 -split-sections
  GLFW-b:        -O2
  bindings-GLFW: -O2

packages:
  - .
  - location: ../vulkan-api
    extra-dep: true
  - location:
      git: https://github.com/achirkin/GLFW-b
      commit: 1c34109deeb5ed465df783830c2ecf54a8daa873
    extra-dep: true
  - location:
      git: https://github.com/bsl/bindings-GLFW
      commit: 0e0d7272ce9caeb4461acc607b6536e84d048a4a
    extra-dep: true
