resolver: nightly-2018-04-12

ghc-options:
  vulkan-api:    -O2
  GLFW-b:        -O2
  bindings-GLFW: -O2

flags:
  vulkan-api:
    useNativeFFI-1-0: true
    useNativeFFI-1-1: false

extra-deps:
  - bindings-GLFW-3.2.1.1
  - GLFW-b-3.2.1.0

packages:
  - .
  - location: ../vulkan-api
    extra-dep: true
  - location: ../../easytensor/easytensor
    extra-dep: true
  - location: ../../easytensor/dimensions
    extra-dep: true
  - location: ../../easytensor/easytensor-vulkan
    extra-dep: true
