resolver: lts-8.21
ghc-options:
  vulkan-api:    -O2
  GLFW-b:        -O2
  bindings-GLFW: -O2

packages:
  - .
  - location: ../vulkan-api
    extra-dep: true
#  - location: ../../GLFW-b
  - location:
      git: https://github.com/achirkin/GLFW-b
      commit: 2c3f9b8d4f1d69960652b8925e5a297b58b20727
    extra-dep: true
#  - location: ../../bindings-GLFW
  - location:
      git: https://github.com/achirkin/bindings-GLFW.git
      commit: acacc06532e23b396c4fa405548fc5ecab53e399
    extra-dep: true
